spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spark_java
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    username: #ADD YOUR EMAIL HERE
    password: #ADD YOU PASSWORD HERE
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB